// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: events.proto

package bus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartTrigger int32

const (
	RestartTrigger_RESTART_UNKNOWN          RestartTrigger = 0
	RestartTrigger_RESTART_STUCK_TIMEOUT    RestartTrigger = 1
	RestartTrigger_RESTART_DEPLOY_FAIL      RestartTrigger = 2
	RestartTrigger_RESTART_BATTLE_TIMEOUT   RestartTrigger = 3
	RestartTrigger_RESTART_RETURN_HOME_FAIL RestartTrigger = 4
	RestartTrigger_RESTART_APP_CRASH        RestartTrigger = 5
	RestartTrigger_RESTART_HEALTH_CHECK     RestartTrigger = 6
)

// Enum value maps for RestartTrigger.
var (
	RestartTrigger_name = map[int32]string{
		0: "RESTART_UNKNOWN",
		1: "RESTART_STUCK_TIMEOUT",
		2: "RESTART_DEPLOY_FAIL",
		3: "RESTART_BATTLE_TIMEOUT",
		4: "RESTART_RETURN_HOME_FAIL",
		5: "RESTART_APP_CRASH",
		6: "RESTART_HEALTH_CHECK",
	}
	RestartTrigger_value = map[string]int32{
		"RESTART_UNKNOWN":          0,
		"RESTART_STUCK_TIMEOUT":    1,
		"RESTART_DEPLOY_FAIL":      2,
		"RESTART_BATTLE_TIMEOUT":   3,
		"RESTART_RETURN_HOME_FAIL": 4,
		"RESTART_APP_CRASH":        5,
		"RESTART_HEALTH_CHECK":     6,
	}
)

func (x RestartTrigger) Enum() *RestartTrigger {
	p := new(RestartTrigger)
	*p = x
	return p
}

func (x RestartTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (RestartTrigger) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x RestartTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartTrigger.Descriptor instead.
func (RestartTrigger) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type GameState int32

const (
	GameState_UNKNOWN         GameState = 0
	GameState_MAIN_VILLAGE    GameState = 1
	GameState_BUILDER_BASE    GameState = 2
	GameState_BATTLE          GameState = 3
	GameState_BATTLE_END      GameState = 4
	GameState_ARMY_CAMP       GameState = 5
	GameState_SEARCH_MAP      GameState = 6
	GameState_FIND_MATCH      GameState = 7
	GameState_SETTINGS        GameState = 8
	GameState_OBSTACLE_DIALOG GameState = 9
	GameState_GEM_DIALOG      GameState = 10
	GameState_CHAT_OPEN       GameState = 11
	GameState_SHIELD_INFO     GameState = 12
	GameState_RETURN_HOME     GameState = 13
	GameState_LOADING         GameState = 14
	GameState_WELCOME_BACK    GameState = 15
	GameState_ARMY_SELECTION  GameState = 16
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "MAIN_VILLAGE",
		2:  "BUILDER_BASE",
		3:  "BATTLE",
		4:  "BATTLE_END",
		5:  "ARMY_CAMP",
		6:  "SEARCH_MAP",
		7:  "FIND_MATCH",
		8:  "SETTINGS",
		9:  "OBSTACLE_DIALOG",
		10: "GEM_DIALOG",
		11: "CHAT_OPEN",
		12: "SHIELD_INFO",
		13: "RETURN_HOME",
		14: "LOADING",
		15: "WELCOME_BACK",
		16: "ARMY_SELECTION",
	}
	GameState_value = map[string]int32{
		"UNKNOWN":         0,
		"MAIN_VILLAGE":    1,
		"BUILDER_BASE":    2,
		"BATTLE":          3,
		"BATTLE_END":      4,
		"ARMY_CAMP":       5,
		"SEARCH_MAP":      6,
		"FIND_MATCH":      7,
		"SETTINGS":        8,
		"OBSTACLE_DIALOG": 9,
		"GEM_DIALOG":      10,
		"CHAT_OPEN":       11,
		"SHIELD_INFO":     12,
		"RETURN_HOME":     13,
		"LOADING":         14,
		"WELCOME_BACK":    15,
		"ARMY_SELECTION":  16,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type GameStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	State         GameState              `protobuf:"varint,2,opt,name=state,proto3,enum=clashgo.bus.GameState" json:"state,omitempty"`
	PrevState     GameState              `protobuf:"varint,3,opt,name=prev_state,json=prevState,proto3,enum=clashgo.bus.GameState" json:"prev_state,omitempty"`
	Confidence    int32                  `protobuf:"varint,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ConfirmFrames int32                  `protobuf:"varint,5,opt,name=confirm_frames,json=confirmFrames,proto3" json:"confirm_frames,omitempty"`
	CaptureMs     int64                  `protobuf:"varint,6,opt,name=capture_ms,json=captureMs,proto3" json:"capture_ms,omitempty"`
	Health        *SystemHealth          `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateEvent) Reset() {
	*x = GameStateEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateEvent) ProtoMessage() {}

func (x *GameStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateEvent.ProtoReflect.Descriptor instead.
func (*GameStateEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *GameStateEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GameStateEvent) GetState() GameState {
	if x != nil {
		return x.State
	}
	return GameState_UNKNOWN
}

func (x *GameStateEvent) GetPrevState() GameState {
	if x != nil {
		return x.PrevState
	}
	return GameState_UNKNOWN
}

func (x *GameStateEvent) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GameStateEvent) GetConfirmFrames() int32 {
	if x != nil {
		return x.ConfirmFrames
	}
	return 0
}

func (x *GameStateEvent) GetCaptureMs() int64 {
	if x != nil {
		return x.CaptureMs
	}
	return 0
}

func (x *GameStateEvent) GetHealth() *SystemHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type LootEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Gold          int32                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Elixir        int32                  `protobuf:"varint,3,opt,name=elixir,proto3" json:"elixir,omitempty"`
	DarkElixir    int32                  `protobuf:"varint,4,opt,name=dark_elixir,json=darkElixir,proto3" json:"dark_elixir,omitempty"`
	MeetsReq      bool                   `protobuf:"varint,5,opt,name=meets_req,json=meetsReq,proto3" json:"meets_req,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootEvent) Reset() {
	*x = LootEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootEvent) ProtoMessage() {}

func (x *LootEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootEvent.ProtoReflect.Descriptor instead.
func (*LootEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *LootEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LootEvent) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *LootEvent) GetElixir() int32 {
	if x != nil {
		return x.Elixir
	}
	return 0
}

func (x *LootEvent) GetDarkElixir() int32 {
	if x != nil {
		return x.DarkElixir
	}
	return 0
}

func (x *LootEvent) GetMeetsReq() bool {
	if x != nil {
		return x.MeetsReq
	}
	return false
}

func (x *LootEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LootEvent) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type ActionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionEvent) Reset() {
	*x = ActionEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEvent) ProtoMessage() {}

func (x *ActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEvent.ProtoReflect.Descriptor instead.
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *ActionEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ActionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ActionEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ActionEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ActionEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ActionEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DiagnosticEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	State         GameState              `protobuf:"varint,3,opt,name=state,proto3,enum=clashgo.bus.GameState" json:"state,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FrameJpeg     []byte                 `protobuf:"bytes,5,opt,name=frame_jpeg,json=frameJpeg,proto3" json:"frame_jpeg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticEvent) Reset() {
	*x = DiagnosticEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticEvent) ProtoMessage() {}

func (x *DiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticEvent.ProtoReflect.Descriptor instead.
func (*DiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *DiagnosticEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *DiagnosticEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiagnosticEvent) GetState() GameState {
	if x != nil {
		return x.State
	}
	return GameState_UNKNOWN
}

func (x *DiagnosticEvent) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DiagnosticEvent) GetFrameJpeg() []byte {
	if x != nil {
		return x.FrameJpeg
	}
	return nil
}

type EnrichedStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	BaseState     GameState              `protobuf:"varint,2,opt,name=base_state,json=baseState,proto3,enum=clashgo.bus.GameState" json:"base_state,omitempty"`
	UiElements    []*UIElement           `protobuf:"bytes,3,rep,name=ui_elements,json=uiElements,proto3" json:"ui_elements,omitempty"`
	Loot          *LootInfo              `protobuf:"bytes,4,opt,name=loot,proto3" json:"loot,omitempty"`
	Troops        []*TroopCount          `protobuf:"bytes,5,rep,name=troops,proto3" json:"troops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedStateEvent) Reset() {
	*x = EnrichedStateEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedStateEvent) ProtoMessage() {}

func (x *EnrichedStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedStateEvent.ProtoReflect.Descriptor instead.
func (*EnrichedStateEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichedStateEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *EnrichedStateEvent) GetBaseState() GameState {
	if x != nil {
		return x.BaseState
	}
	return GameState_UNKNOWN
}

func (x *EnrichedStateEvent) GetUiElements() []*UIElement {
	if x != nil {
		return x.UiElements
	}
	return nil
}

func (x *EnrichedStateEvent) GetLoot() *LootInfo {
	if x != nil {
		return x.Loot
	}
	return nil
}

func (x *EnrichedStateEvent) GetTroops() []*TroopCount {
	if x != nil {
		return x.Troops
	}
	return nil
}

type UIElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ElementType   string                 `protobuf:"bytes,5,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIElement) Reset() {
	*x = UIElement{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIElement) ProtoMessage() {}

func (x *UIElement) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIElement.ProtoReflect.Descriptor instead.
func (*UIElement) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *UIElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UIElement) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UIElement) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *UIElement) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *UIElement) GetElementType() string {
	if x != nil {
		return x.ElementType
	}
	return ""
}

type LootInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int32                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Elixir        int32                  `protobuf:"varint,2,opt,name=elixir,proto3" json:"elixir,omitempty"`
	DarkElixir    int32                  `protobuf:"varint,3,opt,name=dark_elixir,json=darkElixir,proto3" json:"dark_elixir,omitempty"`
	Valid         bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootInfo) Reset() {
	*x = LootInfo{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootInfo) ProtoMessage() {}

func (x *LootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootInfo.ProtoReflect.Descriptor instead.
func (*LootInfo) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *LootInfo) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *LootInfo) GetElixir() int32 {
	if x != nil {
		return x.Elixir
	}
	return 0
}

func (x *LootInfo) GetDarkElixir() int32 {
	if x != nil {
		return x.DarkElixir
	}
	return 0
}

func (x *LootInfo) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type TroopCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Slot          int32                  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TroopCount) Reset() {
	*x = TroopCount{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TroopCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TroopCount) ProtoMessage() {}

func (x *TroopCount) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TroopCount.ProtoReflect.Descriptor instead.
func (*TroopCount) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *TroopCount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TroopCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TroopCount) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type SystemHealth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdbConnected     bool                   `protobuf:"varint,1,opt,name=adb_connected,json=adbConnected,proto3" json:"adb_connected,omitempty"`
	LastCaptureMs    int64                  `protobuf:"varint,2,opt,name=last_capture_ms,json=lastCaptureMs,proto3" json:"last_capture_ms,omitempty"`
	AvgCaptureMs     float64                `protobuf:"fixed64,3,opt,name=avg_capture_ms,json=avgCaptureMs,proto3" json:"avg_capture_ms,omitempty"`
	ConsecutiveFails int32                  `protobuf:"varint,4,opt,name=consecutive_fails,json=consecutiveFails,proto3" json:"consecutive_fails,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemHealth) Reset() {
	*x = SystemHealth{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHealth) ProtoMessage() {}

func (x *SystemHealth) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHealth.ProtoReflect.Descriptor instead.
func (*SystemHealth) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *SystemHealth) GetAdbConnected() bool {
	if x != nil {
		return x.AdbConnected
	}
	return false
}

func (x *SystemHealth) GetLastCaptureMs() int64 {
	if x != nil {
		return x.LastCaptureMs
	}
	return 0
}

func (x *SystemHealth) GetAvgCaptureMs() float64 {
	if x != nil {
		return x.AvgCaptureMs
	}
	return 0
}

func (x *SystemHealth) GetConsecutiveFails() int32 {
	if x != nil {
		return x.ConsecutiveFails
	}
	return 0
}

// ScreenEvent is emitted on every frame capture attempt by the capture loop.
// It is the heartbeat of observability: latency, phash, and diff-vs-previous
// allow the terminal AI to reconstruct what changed at any moment.
type ScreenEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs      int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Width            int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	CaptureLatencyMs int64                  `protobuf:"varint,4,opt,name=capture_latency_ms,json=captureLatencyMs,proto3" json:"capture_latency_ms,omitempty"`
	FrameHash        string                 `protobuf:"bytes,5,opt,name=frame_hash,json=frameHash,proto3" json:"frame_hash,omitempty"`
	PreviousHash     string                 `protobuf:"bytes,6,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	DiffPercent      int32                  `protobuf:"varint,7,opt,name=diff_percent,json=diffPercent,proto3" json:"diff_percent,omitempty"`
	Empty            bool                   `protobuf:"varint,8,opt,name=empty,proto3" json:"empty,omitempty"`
	Error            string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	AttackId         string                 `protobuf:"bytes,10,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScreenEvent) Reset() {
	*x = ScreenEvent{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenEvent) ProtoMessage() {}

func (x *ScreenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenEvent.ProtoReflect.Descriptor instead.
func (*ScreenEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *ScreenEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ScreenEvent) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenEvent) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenEvent) GetCaptureLatencyMs() int64 {
	if x != nil {
		return x.CaptureLatencyMs
	}
	return 0
}

func (x *ScreenEvent) GetFrameHash() string {
	if x != nil {
		return x.FrameHash
	}
	return ""
}

func (x *ScreenEvent) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *ScreenEvent) GetDiffPercent() int32 {
	if x != nil {
		return x.DiffPercent
	}
	return 0
}

func (x *ScreenEvent) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *ScreenEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScreenEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

// TapEvent is emitted for every tap path (pinpoint, color, template, blind)
// with the tier used, attempt count, coordinates, confidence, and outcome.
type TapEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs    int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TargetName     string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	TierUsed       string                 `protobuf:"bytes,3,opt,name=tier_used,json=tierUsed,proto3" json:"tier_used,omitempty"` // "pinpoint" | "color" | "template" | "blind"
	Attempt        int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	X              int32                  `protobuf:"varint,5,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32                  `protobuf:"varint,6,opt,name=y,proto3" json:"y,omitempty"`
	RefX           int32                  `protobuf:"varint,7,opt,name=ref_x,json=refX,proto3" json:"ref_x,omitempty"` // 860x732 reference coordinates
	RefY           int32                  `protobuf:"varint,8,opt,name=ref_y,json=refY,proto3" json:"ref_y,omitempty"`
	Confidence     float32                `protobuf:"fixed32,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TotalLatencyMs int64                  `protobuf:"varint,10,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	Success        bool                   `protobuf:"varint,11,opt,name=success,proto3" json:"success,omitempty"`
	FailureReason  string                 `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	YellowZone     bool                   `protobuf:"varint,13,opt,name=yellow_zone,json=yellowZone,proto3" json:"yellow_zone,omitempty"`
	AttackId       string                 `protobuf:"bytes,14,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	SlotName       string                 `protobuf:"bytes,15,opt,name=slot_name,json=slotName,proto3" json:"slot_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TapEvent) Reset() {
	*x = TapEvent{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapEvent) ProtoMessage() {}

func (x *TapEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapEvent.ProtoReflect.Descriptor instead.
func (*TapEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *TapEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TapEvent) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *TapEvent) GetTierUsed() string {
	if x != nil {
		return x.TierUsed
	}
	return ""
}

func (x *TapEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TapEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TapEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TapEvent) GetRefX() int32 {
	if x != nil {
		return x.RefX
	}
	return 0
}

func (x *TapEvent) GetRefY() int32 {
	if x != nil {
		return x.RefY
	}
	return 0
}

func (x *TapEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TapEvent) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *TapEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TapEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *TapEvent) GetYellowZone() bool {
	if x != nil {
		return x.YellowZone
	}
	return false
}

func (x *TapEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

func (x *TapEvent) GetSlotName() string {
	if x != nil {
		return x.SlotName
	}
	return ""
}

// SequenceStepEvent tracks each step in the clickSequence (Attack ->
// FindMatch -> ArmyArrow -> Army1 -> Battle).
type SequenceStepEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SequenceId    string                 `protobuf:"bytes,2,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	StepIndex     int32                  `protobuf:"varint,3,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	StepName      string                 `protobuf:"bytes,4,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Outcome       string                 `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"` // "ok" | "retry" | "fail"
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	TierUsed      string                 `protobuf:"bytes,7,opt,name=tier_used,json=tierUsed,proto3" json:"tier_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceStepEvent) Reset() {
	*x = SequenceStepEvent{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceStepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceStepEvent) ProtoMessage() {}

func (x *SequenceStepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceStepEvent.ProtoReflect.Descriptor instead.
func (*SequenceStepEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *SequenceStepEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *SequenceStepEvent) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *SequenceStepEvent) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *SequenceStepEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *SequenceStepEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *SequenceStepEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SequenceStepEvent) GetTierUsed() string {
	if x != nil {
		return x.TierUsed
	}
	return ""
}

// ClassifierEvent emits the classifier's structured verdict: top score plus
// alternatives, so a terminal AI can spot confidence drift over time.
type ClassifierEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs       int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	State             GameState              `protobuf:"varint,2,opt,name=state,proto3,enum=clashgo.bus.GameState" json:"state,omitempty"`
	PrevState         GameState              `protobuf:"varint,3,opt,name=prev_state,json=prevState,proto3,enum=clashgo.bus.GameState" json:"prev_state,omitempty"`
	TopScore          int32                  `protobuf:"varint,4,opt,name=top_score,json=topScore,proto3" json:"top_score,omitempty"`
	AlternativeScores map[string]int32       `protobuf:"bytes,5,rep,name=alternative_scores,json=alternativeScores,proto3" json:"alternative_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ConfirmFrames     int32                  `protobuf:"varint,6,opt,name=confirm_frames,json=confirmFrames,proto3" json:"confirm_frames,omitempty"`
	CaptureMs         int64                  `protobuf:"varint,7,opt,name=capture_ms,json=captureMs,proto3" json:"capture_ms,omitempty"`
	AttackId          string                 `protobuf:"bytes,8,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassifierEvent) Reset() {
	*x = ClassifierEvent{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifierEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifierEvent) ProtoMessage() {}

func (x *ClassifierEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifierEvent.ProtoReflect.Descriptor instead.
func (*ClassifierEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *ClassifierEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ClassifierEvent) GetState() GameState {
	if x != nil {
		return x.State
	}
	return GameState_UNKNOWN
}

func (x *ClassifierEvent) GetPrevState() GameState {
	if x != nil {
		return x.PrevState
	}
	return GameState_UNKNOWN
}

func (x *ClassifierEvent) GetTopScore() int32 {
	if x != nil {
		return x.TopScore
	}
	return 0
}

func (x *ClassifierEvent) GetAlternativeScores() map[string]int32 {
	if x != nil {
		return x.AlternativeScores
	}
	return nil
}

func (x *ClassifierEvent) GetConfirmFrames() int32 {
	if x != nil {
		return x.ConfirmFrames
	}
	return 0
}

func (x *ClassifierEvent) GetCaptureMs() int64 {
	if x != nil {
		return x.CaptureMs
	}
	return 0
}

func (x *ClassifierEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

// DeployEvent captures per-phase / per-unit deployment decisions with the
// surrounding red-zone + slot context, so a trajectory can be reconstructed
// without looking at PNGs.
type DeployEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	AttackId      string                 `protobuf:"bytes,2,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	SlotX         int32                  `protobuf:"varint,5,opt,name=slot_x,json=slotX,proto3" json:"slot_x,omitempty"`
	SlotY         int32                  `protobuf:"varint,6,opt,name=slot_y,json=slotY,proto3" json:"slot_y,omitempty"`
	SlotIdx       int32                  `protobuf:"varint,7,opt,name=slot_idx,json=slotIdx,proto3" json:"slot_idx,omitempty"`
	SlotCategory  string                 `protobuf:"bytes,8,opt,name=slot_category,json=slotCategory,proto3" json:"slot_category,omitempty"` // "Troop" | "Hero" | "Siege" | "Spell" | "CC"
	BeforeCount   int32                  `protobuf:"varint,9,opt,name=before_count,json=beforeCount,proto3" json:"before_count,omitempty"`
	AfterCount    int32                  `protobuf:"varint,10,opt,name=after_count,json=afterCount,proto3" json:"after_count,omitempty"`
	TapTier       int32                  `protobuf:"varint,11,opt,name=tap_tier,json=tapTier,proto3" json:"tap_tier,omitempty"`
	RedZoneValid  bool                   `protobuf:"varint,12,opt,name=red_zone_valid,json=redZoneValid,proto3" json:"red_zone_valid,omitempty"`
	RedZoneX      int32                  `protobuf:"varint,13,opt,name=red_zone_x,json=redZoneX,proto3" json:"red_zone_x,omitempty"`
	RedZoneY      int32                  `protobuf:"varint,14,opt,name=red_zone_y,json=redZoneY,proto3" json:"red_zone_y,omitempty"`
	RedZoneW      int32                  `protobuf:"varint,15,opt,name=red_zone_w,json=redZoneW,proto3" json:"red_zone_w,omitempty"`
	RedZoneH      int32                  `protobuf:"varint,16,opt,name=red_zone_h,json=redZoneH,proto3" json:"red_zone_h,omitempty"`
	DeployPoints  []int32                `protobuf:"varint,17,rep,packed,name=deploy_points,json=deployPoints,proto3" json:"deploy_points,omitempty"` // packed x1,y1,x2,y2,...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployEvent) Reset() {
	*x = DeployEvent{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployEvent) ProtoMessage() {}

func (x *DeployEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployEvent.ProtoReflect.Descriptor instead.
func (*DeployEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *DeployEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *DeployEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

func (x *DeployEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DeployEvent) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *DeployEvent) GetSlotX() int32 {
	if x != nil {
		return x.SlotX
	}
	return 0
}

func (x *DeployEvent) GetSlotY() int32 {
	if x != nil {
		return x.SlotY
	}
	return 0
}

func (x *DeployEvent) GetSlotIdx() int32 {
	if x != nil {
		return x.SlotIdx
	}
	return 0
}

func (x *DeployEvent) GetSlotCategory() string {
	if x != nil {
		return x.SlotCategory
	}
	return ""
}

func (x *DeployEvent) GetBeforeCount() int32 {
	if x != nil {
		return x.BeforeCount
	}
	return 0
}

func (x *DeployEvent) GetAfterCount() int32 {
	if x != nil {
		return x.AfterCount
	}
	return 0
}

func (x *DeployEvent) GetTapTier() int32 {
	if x != nil {
		return x.TapTier
	}
	return 0
}

func (x *DeployEvent) GetRedZoneValid() bool {
	if x != nil {
		return x.RedZoneValid
	}
	return false
}

func (x *DeployEvent) GetRedZoneX() int32 {
	if x != nil {
		return x.RedZoneX
	}
	return 0
}

func (x *DeployEvent) GetRedZoneY() int32 {
	if x != nil {
		return x.RedZoneY
	}
	return 0
}

func (x *DeployEvent) GetRedZoneW() int32 {
	if x != nil {
		return x.RedZoneW
	}
	return 0
}

func (x *DeployEvent) GetRedZoneH() int32 {
	if x != nil {
		return x.RedZoneH
	}
	return 0
}

func (x *DeployEvent) GetDeployPoints() []int32 {
	if x != nil {
		return x.DeployPoints
	}
	return nil
}

// AttackSummaryEvent fires once per attack with aggregated outcome.
type AttackSummaryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs     int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	AttackId        string                 `protobuf:"bytes,2,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	Strategy        string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	TargetEdge      string                 `protobuf:"bytes,4,opt,name=target_edge,json=targetEdge,proto3" json:"target_edge,omitempty"`
	DeploySuccess   bool                   `protobuf:"varint,5,opt,name=deploy_success,json=deploySuccess,proto3" json:"deploy_success,omitempty"`
	Undeployed      int32                  `protobuf:"varint,6,opt,name=undeployed,proto3" json:"undeployed,omitempty"`
	Stars           int32                  `protobuf:"varint,7,opt,name=stars,proto3" json:"stars,omitempty"`
	LootGold        int32                  `protobuf:"varint,8,opt,name=loot_gold,json=lootGold,proto3" json:"loot_gold,omitempty"`
	LootElixir      int32                  `protobuf:"varint,9,opt,name=loot_elixir,json=lootElixir,proto3" json:"loot_elixir,omitempty"`
	LootDe          int32                  `protobuf:"varint,10,opt,name=loot_de,json=lootDe,proto3" json:"loot_de,omitempty"`
	BonusGold       int32                  `protobuf:"varint,11,opt,name=bonus_gold,json=bonusGold,proto3" json:"bonus_gold,omitempty"`
	BonusElixir     int32                  `protobuf:"varint,12,opt,name=bonus_elixir,json=bonusElixir,proto3" json:"bonus_elixir,omitempty"`
	BonusDe         int32                  `protobuf:"varint,13,opt,name=bonus_de,json=bonusDe,proto3" json:"bonus_de,omitempty"`
	TotalDurationMs int64                  `protobuf:"varint,14,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`
	TapCount        int32                  `protobuf:"varint,15,opt,name=tap_count,json=tapCount,proto3" json:"tap_count,omitempty"`
	FailCount       int32                  `protobuf:"varint,16,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackSummaryEvent) Reset() {
	*x = AttackSummaryEvent{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackSummaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackSummaryEvent) ProtoMessage() {}

func (x *AttackSummaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackSummaryEvent.ProtoReflect.Descriptor instead.
func (*AttackSummaryEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *AttackSummaryEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AttackSummaryEvent) GetAttackId() string {
	if x != nil {
		return x.AttackId
	}
	return ""
}

func (x *AttackSummaryEvent) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *AttackSummaryEvent) GetTargetEdge() string {
	if x != nil {
		return x.TargetEdge
	}
	return ""
}

func (x *AttackSummaryEvent) GetDeploySuccess() bool {
	if x != nil {
		return x.DeploySuccess
	}
	return false
}

func (x *AttackSummaryEvent) GetUndeployed() int32 {
	if x != nil {
		return x.Undeployed
	}
	return 0
}

func (x *AttackSummaryEvent) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *AttackSummaryEvent) GetLootGold() int32 {
	if x != nil {
		return x.LootGold
	}
	return 0
}

func (x *AttackSummaryEvent) GetLootElixir() int32 {
	if x != nil {
		return x.LootElixir
	}
	return 0
}

func (x *AttackSummaryEvent) GetLootDe() int32 {
	if x != nil {
		return x.LootDe
	}
	return 0
}

func (x *AttackSummaryEvent) GetBonusGold() int32 {
	if x != nil {
		return x.BonusGold
	}
	return 0
}

func (x *AttackSummaryEvent) GetBonusElixir() int32 {
	if x != nil {
		return x.BonusElixir
	}
	return 0
}

func (x *AttackSummaryEvent) GetBonusDe() int32 {
	if x != nil {
		return x.BonusDe
	}
	return 0
}

func (x *AttackSummaryEvent) GetTotalDurationMs() int64 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

func (x *AttackSummaryEvent) GetTapCount() int32 {
	if x != nil {
		return x.TapCount
	}
	return 0
}

func (x *AttackSummaryEvent) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

type RestartEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs     int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Trigger         RestartTrigger         `protobuf:"varint,2,opt,name=trigger,proto3,enum=clashgo.bus.RestartTrigger" json:"trigger,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	LastActionAgeMs int64                  `protobuf:"varint,4,opt,name=last_action_age_ms,json=lastActionAgeMs,proto3" json:"last_action_age_ms,omitempty"`
	LastState       string                 `protobuf:"bytes,5,opt,name=last_state,json=lastState,proto3" json:"last_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestartEvent) Reset() {
	*x = RestartEvent{}
	mi := &file_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartEvent) ProtoMessage() {}

func (x *RestartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartEvent.ProtoReflect.Descriptor instead.
func (*RestartEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{15}
}

func (x *RestartEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RestartEvent) GetTrigger() RestartTrigger {
	if x != nil {
		return x.Trigger
	}
	return RestartTrigger_RESTART_UNKNOWN
}

func (x *RestartEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RestartEvent) GetLastActionAgeMs() int64 {
	if x != nil {
		return x.LastActionAgeMs
	}
	return 0
}

func (x *RestartEvent) GetLastState() string {
	if x != nil {
		return x.LastState
	}
	return ""
}

type StuckEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs      int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	LastState        string                 `protobuf:"bytes,2,opt,name=last_state,json=lastState,proto3" json:"last_state,omitempty"`
	IdleMs           int64                  `protobuf:"varint,3,opt,name=idle_ms,json=idleMs,proto3" json:"idle_ms,omitempty"`
	ConsecutiveFails int32                  `protobuf:"varint,4,opt,name=consecutive_fails,json=consecutiveFails,proto3" json:"consecutive_fails,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StuckEvent) Reset() {
	*x = StuckEvent{}
	mi := &file_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuckEvent) ProtoMessage() {}

func (x *StuckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuckEvent.ProtoReflect.Descriptor instead.
func (*StuckEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{16}
}

func (x *StuckEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *StuckEvent) GetLastState() string {
	if x != nil {
		return x.LastState
	}
	return ""
}

func (x *StuckEvent) GetIdleMs() int64 {
	if x != nil {
		return x.IdleMs
	}
	return 0
}

func (x *StuckEvent) GetConsecutiveFails() int32 {
	if x != nil {
		return x.ConsecutiveFails
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	X2            int32                  `protobuf:"varint,6,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,7,opt,name=y2,proto3" json:"y2,omitempty"`
	DurationMs    int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TargetState   string                 `protobuf:"bytes,9,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Strategy      string                 `protobuf:"bytes,10,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Params        map[string]string      `protobuf:"bytes,11,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{17}
}

func (x *Command) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Command) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Command) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Command) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *Command) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Command) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *Command) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResult) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\vclashgo.bus\"\xb1\x02\n" +
	"\x0eGameStateEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.clashgo.bus.GameStateR\x05state\x125\n" +
	"\n" +
	"prev_state\x18\x03 \x01(\x0e2\x16.clashgo.bus.GameStateR\tprevState\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x05R\n" +
	"confidence\x12%\n" +
	"\x0econfirm_frames\x18\x05 \x01(\x05R\rconfirmFrames\x12\x1d\n" +
	"\n" +
	"capture_ms\x18\x06 \x01(\x03R\tcaptureMs\x121\n" +
	"\x06health\x18\a \x01(\v2\x19.clashgo.bus.SystemHealthR\x06health\"\xcc\x01\n" +
	"\tLootEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x05R\x04gold\x12\x16\n" +
	"\x06elixir\x18\x03 \x01(\x05R\x06elixir\x12\x1f\n" +
	"\vdark_elixir\x18\x04 \x01(\x05R\n" +
	"darkElixir\x12\x1b\n" +
	"\tmeets_req\x18\x05 \x01(\bR\bmeetsReq\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\"\xcb\x01\n" +
	"\vActionEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\x96\x02\n" +
	"\x0fDiagnosticEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.clashgo.bus.GameStateR\x05state\x12C\n" +
	"\adetails\x18\x04 \x03(\v2).clashgo.bus.DiagnosticEvent.DetailsEntryR\adetails\x12\x1d\n" +
	"\n" +
	"frame_jpeg\x18\x05 \x01(\fR\tframeJpeg\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x12EnrichedStateEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x125\n" +
	"\n" +
	"base_state\x18\x02 \x01(\x0e2\x16.clashgo.bus.GameStateR\tbaseState\x127\n" +
	"\vui_elements\x18\x03 \x03(\v2\x16.clashgo.bus.UIElementR\n" +
	"uiElements\x12)\n" +
	"\x04loot\x18\x04 \x01(\v2\x15.clashgo.bus.LootInfoR\x04loot\x12/\n" +
	"\x06troops\x18\x05 \x03(\v2\x17.clashgo.bus.TroopCountR\x06troops\"~\n" +
	"\tUIElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\felement_type\x18\x05 \x01(\tR\velementType\"m\n" +
	"\bLootInfo\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x05R\x04gold\x12\x16\n" +
	"\x06elixir\x18\x02 \x01(\x05R\x06elixir\x12\x1f\n" +
	"\vdark_elixir\x18\x03 \x01(\x05R\n" +
	"darkElixir\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\"J\n" +
	"\n" +
	"TroopCount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x05R\x04slot\"\xae\x01\n" +
	"\fSystemHealth\x12#\n" +
	"\radb_connected\x18\x01 \x01(\bR\fadbConnected\x12&\n" +
	"\x0flast_capture_ms\x18\x02 \x01(\x03R\rlastCaptureMs\x12$\n" +
	"\x0eavg_capture_ms\x18\x03 \x01(\x01R\favgCaptureMs\x12+\n" +
	"\x11consecutive_fails\x18\x04 \x01(\x05R\x10consecutiveFails\"\xbc\x02\n" +
	"\vScreenEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12,\n" +
	"\x12capture_latency_ms\x18\x04 \x01(\x03R\x10captureLatencyMs\x12\x1d\n" +
	"\n" +
	"frame_hash\x18\x05 \x01(\tR\tframeHash\x12#\n" +
	"\rprevious_hash\x18\x06 \x01(\tR\fpreviousHash\x12!\n" +
	"\fdiff_percent\x18\a \x01(\x05R\vdiffPercent\x12\x14\n" +
	"\x05empty\x18\b \x01(\bR\x05empty\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1b\n" +
	"\tattack_id\x18\n" +
	" \x01(\tR\battackId\"\xb1\x03\n" +
	"\bTapEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12\x1b\n" +
	"\ttier_used\x18\x03 \x01(\tR\btierUsed\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\f\n" +
	"\x01x\x18\x05 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x05R\x01y\x12\x13\n" +
	"\x05ref_x\x18\a \x01(\x05R\x04refX\x12\x13\n" +
	"\x05ref_y\x18\b \x01(\x05R\x04refY\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x02R\n" +
	"confidence\x12(\n" +
	"\x10total_latency_ms\x18\n" +
	" \x01(\x03R\x0etotalLatencyMs\x12\x18\n" +
	"\asuccess\x18\v \x01(\bR\asuccess\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\x12\x1f\n" +
	"\vyellow_zone\x18\r \x01(\bR\n" +
	"yellowZone\x12\x1b\n" +
	"\tattack_id\x18\x0e \x01(\tR\battackId\x12\x1b\n" +
	"\tslot_name\x18\x0f \x01(\tR\bslotName\"\xeb\x01\n" +
	"\x11SequenceStepEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vsequence_id\x18\x02 \x01(\tR\n" +
	"sequenceId\x12\x1d\n" +
	"\n" +
	"step_index\x18\x03 \x01(\x05R\tstepIndex\x12\x1b\n" +
	"\tstep_name\x18\x04 \x01(\tR\bstepName\x12\x18\n" +
	"\aoutcome\x18\x05 \x01(\tR\aoutcome\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x1b\n" +
	"\ttier_used\x18\a \x01(\tR\btierUsed\"\xc3\x03\n" +
	"\x0fClassifierEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.clashgo.bus.GameStateR\x05state\x125\n" +
	"\n" +
	"prev_state\x18\x03 \x01(\x0e2\x16.clashgo.bus.GameStateR\tprevState\x12\x1b\n" +
	"\ttop_score\x18\x04 \x01(\x05R\btopScore\x12b\n" +
	"\x12alternative_scores\x18\x05 \x03(\v23.clashgo.bus.ClassifierEvent.AlternativeScoresEntryR\x11alternativeScores\x12%\n" +
	"\x0econfirm_frames\x18\x06 \x01(\x05R\rconfirmFrames\x12\x1d\n" +
	"\n" +
	"capture_ms\x18\a \x01(\x03R\tcaptureMs\x12\x1b\n" +
	"\tattack_id\x18\b \x01(\tR\battackId\x1aD\n" +
	"\x16AlternativeScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x87\x04\n" +
	"\vDeployEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\tattack_id\x18\x02 \x01(\tR\battackId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x15\n" +
	"\x06slot_x\x18\x05 \x01(\x05R\x05slotX\x12\x15\n" +
	"\x06slot_y\x18\x06 \x01(\x05R\x05slotY\x12\x19\n" +
	"\bslot_idx\x18\a \x01(\x05R\aslotIdx\x12#\n" +
	"\rslot_category\x18\b \x01(\tR\fslotCategory\x12!\n" +
	"\fbefore_count\x18\t \x01(\x05R\vbeforeCount\x12\x1f\n" +
	"\vafter_count\x18\n" +
	" \x01(\x05R\n" +
	"afterCount\x12\x19\n" +
	"\btap_tier\x18\v \x01(\x05R\atapTier\x12$\n" +
	"\x0ered_zone_valid\x18\f \x01(\bR\fredZoneValid\x12\x1c\n" +
	"\n" +
	"red_zone_x\x18\r \x01(\x05R\bredZoneX\x12\x1c\n" +
	"\n" +
	"red_zone_y\x18\x0e \x01(\x05R\bredZoneY\x12\x1c\n" +
	"\n" +
	"red_zone_w\x18\x0f \x01(\x05R\bredZoneW\x12\x1c\n" +
	"\n" +
	"red_zone_h\x18\x10 \x01(\x05R\bredZoneH\x12#\n" +
	"\rdeploy_points\x18\x11 \x03(\x05R\fdeployPoints\"\x8a\x04\n" +
	"\x12AttackSummaryEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\tattack_id\x18\x02 \x01(\tR\battackId\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1f\n" +
	"\vtarget_edge\x18\x04 \x01(\tR\n" +
	"targetEdge\x12%\n" +
	"\x0edeploy_success\x18\x05 \x01(\bR\rdeploySuccess\x12\x1e\n" +
	"\n" +
	"undeployed\x18\x06 \x01(\x05R\n" +
	"undeployed\x12\x14\n" +
	"\x05stars\x18\a \x01(\x05R\x05stars\x12\x1b\n" +
	"\tloot_gold\x18\b \x01(\x05R\blootGold\x12\x1f\n" +
	"\vloot_elixir\x18\t \x01(\x05R\n" +
	"lootElixir\x12\x17\n" +
	"\aloot_de\x18\n" +
	" \x01(\x05R\x06lootDe\x12\x1d\n" +
	"\n" +
	"bonus_gold\x18\v \x01(\x05R\tbonusGold\x12!\n" +
	"\fbonus_elixir\x18\f \x01(\x05R\vbonusElixir\x12\x19\n" +
	"\bbonus_de\x18\r \x01(\x05R\abonusDe\x12*\n" +
	"\x11total_duration_ms\x18\x0e \x01(\x03R\x0ftotalDurationMs\x12\x1b\n" +
	"\ttap_count\x18\x0f \x01(\x05R\btapCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x10 \x01(\x05R\tfailCount\"\xcc\x01\n" +
	"\fRestartEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x125\n" +
	"\atrigger\x18\x02 \x01(\x0e2\x1b.clashgo.bus.RestartTriggerR\atrigger\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12+\n" +
	"\x12last_action_age_ms\x18\x04 \x01(\x03R\x0flastActionAgeMs\x12\x1d\n" +
	"\n" +
	"last_state\x18\x05 \x01(\tR\tlastState\"\x94\x01\n" +
	"\n" +
	"StuckEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"last_state\x18\x02 \x01(\tR\tlastState\x12\x17\n" +
	"\aidle_ms\x18\x03 \x01(\x03R\x06idleMs\x12+\n" +
	"\x11consecutive_fails\x18\x04 \x01(\x05R\x10consecutiveFails\"\xf0\x02\n" +
	"\aCommand\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02x2\x18\x06 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\a \x01(\x05R\x02y2\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12!\n" +
	"\ftarget_state\x18\t \x01(\tR\vtargetState\x12\x1a\n" +
	"\bstrategy\x18\n" +
	" \x01(\tR\bstrategy\x128\n" +
	"\x06params\x18\v \x03(\v2 .clashgo.bus.Command.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\rCommandResult\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs*\xc4\x01\n" +
	"\x0eRestartTrigger\x12\x13\n" +
	"\x0fRESTART_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15RESTART_STUCK_TIMEOUT\x10\x01\x12\x17\n" +
	"\x13RESTART_DEPLOY_FAIL\x10\x02\x12\x1a\n" +
	"\x16RESTART_BATTLE_TIMEOUT\x10\x03\x12\x1c\n" +
	"\x18RESTART_RETURN_HOME_FAIL\x10\x04\x12\x15\n" +
	"\x11RESTART_APP_CRASH\x10\x05\x12\x18\n" +
	"\x14RESTART_HEALTH_CHECK\x10\x06*\x9e\x02\n" +
	"\tGameState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fMAIN_VILLAGE\x10\x01\x12\x10\n" +
	"\fBUILDER_BASE\x10\x02\x12\n" +
	"\n" +
	"\x06BATTLE\x10\x03\x12\x0e\n" +
	"\n" +
	"BATTLE_END\x10\x04\x12\r\n" +
	"\tARMY_CAMP\x10\x05\x12\x0e\n" +
	"\n" +
	"SEARCH_MAP\x10\x06\x12\x0e\n" +
	"\n" +
	"FIND_MATCH\x10\a\x12\f\n" +
	"\bSETTINGS\x10\b\x12\x13\n" +
	"\x0fOBSTACLE_DIALOG\x10\t\x12\x0e\n" +
	"\n" +
	"GEM_DIALOG\x10\n" +
	"\x12\r\n" +
	"\tCHAT_OPEN\x10\v\x12\x0f\n" +
	"\vSHIELD_INFO\x10\f\x12\x0f\n" +
	"\vRETURN_HOME\x10\r\x12\v\n" +
	"\aLOADING\x10\x0e\x12\x10\n" +
	"\fWELCOME_BACK\x10\x0f\x12\x12\n" +
	"\x0eARMY_SELECTION\x10\x10B*Z(github.com/Ducky705/ClashGO/internal/busb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_events_proto_goTypes = []any{
	(RestartTrigger)(0),        // 0: clashgo.bus.RestartTrigger
	(GameState)(0),             // 1: clashgo.bus.GameState
	(*GameStateEvent)(nil),     // 2: clashgo.bus.GameStateEvent
	(*LootEvent)(nil),          // 3: clashgo.bus.LootEvent
	(*ActionEvent)(nil),        // 4: clashgo.bus.ActionEvent
	(*DiagnosticEvent)(nil),    // 5: clashgo.bus.DiagnosticEvent
	(*EnrichedStateEvent)(nil), // 6: clashgo.bus.EnrichedStateEvent
	(*UIElement)(nil),          // 7: clashgo.bus.UIElement
	(*LootInfo)(nil),           // 8: clashgo.bus.LootInfo
	(*TroopCount)(nil),         // 9: clashgo.bus.TroopCount
	(*SystemHealth)(nil),       // 10: clashgo.bus.SystemHealth
	(*ScreenEvent)(nil),        // 11: clashgo.bus.ScreenEvent
	(*TapEvent)(nil),           // 12: clashgo.bus.TapEvent
	(*SequenceStepEvent)(nil),  // 13: clashgo.bus.SequenceStepEvent
	(*ClassifierEvent)(nil),    // 14: clashgo.bus.ClassifierEvent
	(*DeployEvent)(nil),        // 15: clashgo.bus.DeployEvent
	(*AttackSummaryEvent)(nil), // 16: clashgo.bus.AttackSummaryEvent
	(*RestartEvent)(nil),       // 17: clashgo.bus.RestartEvent
	(*StuckEvent)(nil),         // 18: clashgo.bus.StuckEvent
	(*Command)(nil),            // 19: clashgo.bus.Command
	(*CommandResult)(nil),      // 20: clashgo.bus.CommandResult
	nil,                        // 21: clashgo.bus.DiagnosticEvent.DetailsEntry
	nil,                        // 22: clashgo.bus.ClassifierEvent.AlternativeScoresEntry
	nil,                        // 23: clashgo.bus.Command.ParamsEntry
}
var file_events_proto_depIdxs = []int32{
	1,  // 0: clashgo.bus.GameStateEvent.state:type_name -> clashgo.bus.GameState
	1,  // 1: clashgo.bus.GameStateEvent.prev_state:type_name -> clashgo.bus.GameState
	10, // 2: clashgo.bus.GameStateEvent.health:type_name -> clashgo.bus.SystemHealth
	1,  // 3: clashgo.bus.DiagnosticEvent.state:type_name -> clashgo.bus.GameState
	21, // 4: clashgo.bus.DiagnosticEvent.details:type_name -> clashgo.bus.DiagnosticEvent.DetailsEntry
	1,  // 5: clashgo.bus.EnrichedStateEvent.base_state:type_name -> clashgo.bus.GameState
	7,  // 6: clashgo.bus.EnrichedStateEvent.ui_elements:type_name -> clashgo.bus.UIElement
	8,  // 7: clashgo.bus.EnrichedStateEvent.loot:type_name -> clashgo.bus.LootInfo
	9,  // 8: clashgo.bus.EnrichedStateEvent.troops:type_name -> clashgo.bus.TroopCount
	1,  // 9: clashgo.bus.ClassifierEvent.state:type_name -> clashgo.bus.GameState
	1,  // 10: clashgo.bus.ClassifierEvent.prev_state:type_name -> clashgo.bus.GameState
	22, // 11: clashgo.bus.ClassifierEvent.alternative_scores:type_name -> clashgo.bus.ClassifierEvent.AlternativeScoresEntry
	0,  // 12: clashgo.bus.RestartEvent.trigger:type_name -> clashgo.bus.RestartTrigger
	23, // 13: clashgo.bus.Command.params:type_name -> clashgo.bus.Command.ParamsEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
